swagger: '2.0'
info:
  description: Form3 Exercise
  version: '0.1'
  title: Form3 Exercise
  termsOfService: ''
basePath: /
schemes:
  - https
paths:
  /v1/payments:
    get:
      summary: Get a list of payments
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            This is the request object that passes the Article we want
            recommendations based on and some query parameters and filters
          required: true
          schema:
            $ref: '#/definitions/payments-list-request'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/payments-list-response'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
definitions:
  error:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 404
      status:
        type: string
        example: Bad Request
  payment:
    type: object
    properties:
      type:
        type: string
        enum:
          - "Payment"
        example: "Payment"
      id:
        type: string
        example: "4ee3a8d8-ca7b-4290-a52c-dd5b6165ec43"
      version:
        type: integer
        format: int32
        example: 0
      organization_id:
        type: string
        example: "743d5b63-8e6f-432e-a8fa-c5d8d2ee5fcb"
      attributes:
        $ref: '#/definitions/payment-attributes'
  payment-attributes:
    type: object
    properties:
      amount:
        type: string
        example: "199.99"
      beneficiary_party:
        $ref: '#/definitions/payment-party'
      charges_information:
        $ref: '#/definitions/payment-charges-info'
      currency:
        $ref: "#/definitions/currency"
      debtor_party:
        $ref: '#/definitions/payment-party'
      end_to_end_reference:
        type: string
        example: "Wil piano Jan"
      fx:
        type: object
        properties:
          contract_reference:
            type: string
            example: "FX123"
          exchange_rate:
            type: string
            example: "2.00000"
          original_amount:
            type: string
            example: "200.42"
          original_currency:
            type: string
            example: "USD"
      numeric_reference":
        type: string
        example: "1002001"
      payment_id:
        type: string
        example: "123456789012345678"
      payment_purpose:
        type: string
        example: "Paying for goods/services"
      payment_scheme:
        type: string
        example: "FPS"
      payment_type:
        type: string
        example: "Credit"
      processing_date:
        type: string
        example: "2017-01-18"
      reference:
        type: string
        example: "Payment for Em's piano lessons"
      scheme_payment_sub_type:
        type: string
        example: "InternetBanking"
      scheme_payment_type:
        type: string
        example: "ImmediatePayment"
      sponsor_party:
        type: object
        properties:
          account_number:
            type: string
            example: "56781234"
          bank_id:
            type: string
            example: "123123"
          bank_id_code:
            type: string
            example: "GBDSC"
  payment-party:
    type: object
    properties:
      account_name:
        type: string
        example: "W Owens"
      account_number:
        type: string
        example: "31926819"
      account_number_code:
        type: string
        example: "BBAN"
      account_type:
        type: number
        format: int32
        example: 0
      address:
        type: string
        example: "1 The Beneficiary Localtown SE2"
      bank_id:
        type: string
        example: "403000"
      bank_id_code:
        type: string
        example: "GBDSC"
      name:
        type: string
        example: "Wilfred Jeremiah Owens"
  payment-charges-info:
    type: object
    properties:
      bearer_code:
        type: string
        enum:
          - SHAR
        example: SHAR
      sender_charges:
        type: array
        items:
          $ref: "#/definitions/payment-charges"
      receiver_charges_amount:
        type: string
        example: "1.00"
      receiver_charges_currency:
        $ref: "#/definitions/currency"
  payment-charges:
    type: object
    properties:
      amount:
        type: string
        example: "5.00"
      currency:
        $ref: "#/definitions/currency"
  currency:
    type: string
    enum:
      - "GBP"
      - "EUR"
      - "USD"
  payments-list-request:
    type: object
    properties:
      type:
        type: string

  payments-list-response:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/payment'
      links:
        type: array
        items:
          type: string
          format: url


